# Generated by Django 5.1.1 on 2024-10-06 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agresor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Anonimo', max_length=50)),
                ('primerApellido', models.CharField(default='Anonimo', max_length=50)),
                ('segundoApellido', models.CharField(default='Anonimo', max_length=50)),
                ('tipoDocumento', models.CharField(default='No se especifica', max_length=50)),
                ('numeroDocumento', models.CharField(default='No se especifica', max_length=50)),
                ('ciudadNacimiento', models.CharField(default='No se especifica', max_length=50)),
                ('ciudadResidencia', models.CharField(default='No se especifica', max_length=50)),
                ('antecedentesPenales', models.TextField(default='No se conocen', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Anonimo', max_length=50)),
                ('primerApellido', models.CharField(default='Anonimo', max_length=50)),
                ('segundoApellido', models.CharField(default='Anonimo', max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('tipoDocumento', models.CharField(default='No tiene', max_length=50)),
                ('numeroDocumento', models.CharField(default='No se sabe', max_length=50)),
                ('ciudadNacimiento', models.CharField(default='No esta definida', max_length=50)),
                ('ciudadRecidencia', models.CharField(default='No esta definida', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradoDeViolencia', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(default=None)),
                ('descripcion', models.TextField(default='No hay suficiente informacion para generar una descripcion', max_length=1000)),
                ('prevenciones', models.TextField(default='No estan disponibles', max_length=1000)),
                ('ubicacion', models.CharField(default='No se conoce la ubicacion de la demanda', max_length=50)),
                ('tipoDeDenuncia', models.CharField(default='No se especifica', max_length=20)),
                ('agresor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elementosUsuario.agresor')),
                ('victima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elementosUsuario.victima')),
            ],
        ),
    ]
