# Generated by Django 5.1.3 on 2024-11-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementosUsuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agresor',
            name='entidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='titulo',
            field=models.CharField(default='No cuenta con titulo', max_length=100),
        ),
    ]
