# Generated by Django 5.1.3 on 2024-11-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elementosUsuario', '0002_agresor_entidad_denuncia_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agresor',
            name='antecedentesPenales',
        ),
    ]
