# Generated by Django 5.1.3 on 2024-11-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementosUsuario', '0003_remove_agresor_antecedentespenales'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='ciudad',
            field=models.CharField(default='No se especifica', max_length=50),
        ),
    ]
